import Nav from '@/Components/Nav/Nav'
import 'styles/globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

{/* For background */}
        <div className='main'>
          <div className='gradient' />
        </div>

        <main>
          <Nav></Nav>
          {children}
          <Footer></Footer>
        </main>
      </body>
    </html>
  )
}
